### ISSUE TITLE
Future edits for new cex.io pairs?

### ISSUE THREAD

**Issue by reedog117** [Eloque/CexControl#12]
Are any future versions going to be released for all the new currency pairs that cex.io now has available?

**Comment by Eloque** [comment]
I try to update the pairs where needed. Basically, if you can mine it and trade it, it should be in the script as well. Is there a pair you are missing?

**Comment by reedog117** [comment]
I remember before we just had GHS/BTC and GHS/NMC... now GHS/LTC and GHS/USD exists as well.  It would also be interesting to try to perform arbitrage between LTC, BTC, and USD, considering now its possible to trade between all three.

**Comment by Eloque** [comment]
IXC  to GHS via BTC is there.

NMC, IXC and BTC all trade to GHS, arbitrage has been made, but I didn't publish that because it never made any money. The market is to well balanced on just Cex.IO to make a difference.

The script is meant to reinvest, not designed to do autotrading beyond a basic few moves.

**Comment by S0AndS0** [comment]
When NMC/GHS went down on cex and this script was no-longer able to arbitrate, I devoted my time to coming to understand the CexControl.py script better. Thankfully Python is similar enough to what I've already studied that very much of the source code is readable. Because of these factors I can offer you an updated version that does arbitrage between LTC/BTC=>GHS 
https://github.com/S0AndS0/Debian-Kit-Mods/tree/master/Examples/CexBotMods
the CexControl.py file in the above directory does what the old NMC/BTC=>GHS script did but with Litecoins instead. This version is what I have running on my Android (shrooted Linux Debian) and it's working flawlessly. 
The other ~.py files in the above directory will be my efforts to have more arbitrage options supported. But may be expanded to a full forking.

@reedog117 do you want a 'cash-out' script or one that compairs LTC/USD=>GHS & BTC/USD=>GHS? Because if you check what I'm trying with DRK/BTC=>GHS & DRK/LTC=>GHS I've only a few more bugs to figure out before I can start making all pare options convert to GHS . Though thats going to make the line count go up for this file... @Eloque do you happen to have a good resource for brushing up on Pythin so I don't go bugging people with noobe questions? I want to separate some of the sections of the script such that it's easier to add and remove pares and I'd like to help with a GUI when I've a bit more knowledge.

**Comment by Eloque** [comment]
Glad the code is readable :) 
In any case, I never pursued the arbitrage things, because it never made any real profits.
Is your experience different?

**Comment by S0AndS0** [comment]
Readable but modders can always use more notes or comments to go by; I could use some help on how the target coin variable is set correctly because my DRK additions are causing a short-out in trading between LTC/BTC=>GHS

Arbitrage is worth persuing. Though it only popped off when set to 100% a few time per day (back when NMC/GHS was allowed) it was worth it to me because I'm chilling at the shallow-end of the hashing pool and every little bit helps. Now with LTC instead it has been far less, once or twice a day, but I'm also not mining LTC with 100% up-time and the market for GHS/LTC is still gaining speed so at the moment it's slow going but I've fait it'll get better as more third party apps come back with updates to match cex.

I had time with someone else that's been looking at your code today and took note in the same directory as was previosly posted; looks like I'll be doing a full fork to keep things clean.
